version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Terraform providers
  - package-ecosystem: "terraform"
    directory: "/environments/prod"
    schedule:
      interval: "weekly"
