namespace: book-info

image:
  repository: docker.io/istio
  tag: "1.20.3"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 384Mi

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 80

gateway:
  name: ext-book-info-gateway
  className: gke-l7-global-external-managed
  port: 8080

healthCheck:
  checkIntervalSec: 15
  timeoutSec: 5
  healthyThreshold: 1
  unhealthyThreshold: 2
  requestPath: /
  port: 9080

backendPolicy:
  connectionDraining:
    drainingTimeoutSec: 30
  logging:
    enabled: true
    sampleRate: "1.0"
---

