# Service for nginx deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: beta
  labels:
    app: nginx
    service: nginx
spec:
  ports:
  - port: 8080
    targetPort: 80
    name: http
  selector:
    app: nginx
---

# Service account for nginx deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: beta
  labels:
    account: nginx
---

# Deployment for nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: beta
  labels:
    app: nginx
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: docker.io/nginx:alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      terminationGracePeriodSeconds: 30
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
---
