apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: team-b-http-route
  namespace: team-b
spec:
  parentRefs:
  - name: ext-gateway
    namespace: platform
    sectionName: http-8081

  rules:
  - matches:
    - path:
        type: Exact
        value: /
    backendRefs:
    - name: nginx
      port: 8081
      weight: 100
