{{- range $name, $team := .Values.teams }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $name }}-resource-quota
  namespace: {{ $name }}
spec:
  hard:
    requests.cpu: {{ $team.quota.cpu.requests | quote }}
    requests.memory: {{ $team.quota.memory.requests }}
    limits.cpu: {{ $team.quota.cpu.limits | quote }}
    limits.memory: {{ $team.quota.memory.limits }}
    pods: {{ $team.quota.pods | quote }}
    services: {{ $team.quota.services | quote }}
{{- end }}
