{{- range $name, $team := .Values.teams }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: {{ $name }}
  labels:
    account: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ $name }}
  labels:
    app: nginx
    version: v1
spec:
  replicas: {{ $team.replicas }}
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: {{ $team.image }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ $team.resources.requests.cpu }}
            memory: {{ $team.resources.requests.memory }}
          limits:
            cpu: {{ $team.resources.limits.cpu }}
            memory: {{ $team.resources.limits.memory }}
        ports:
        - containerPort: 80
{{- end }}
