apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: book-info-health-check
  namespace: book-info
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 9080
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: productpage
