apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: team-a-health-check
  namespace: team-a
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: nginx
