apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: book-info-backend-policy
  namespace: {{ .Values.namespace }}
spec:
  default:
    connectionDraining:
      drainingTimeoutSec: {{ .Values.backendPolicy.connectionDraining.drainingTimeoutSec }}
    logging:
      enabled: {{ .Values.backendPolicy.logging.enabled }}
      sampleRate: {{ .Values.backendPolicy.logging.sampleRate }}
  targetRef:
    group: ""
    kind: Service
    name: productpage
---


