---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: {{ .Values.image.repository }}/examples-bookinfo-details-v1:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: {{ .Values.image.repository }}/examples-bookinfo-ratings-v1:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 9080
{{- range list "v1" "v2" "v3" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-{{ . }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: reviews
    version: {{ . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: {{ . }}
  template:
    metadata:
      labels:
        app: reviews
        version: {{ . }}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: {{ $.Values.image.repository }}/examples-bookinfo-reviews-{{ . }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        resources: {{- toYaml $.Values.resources | nindent 10 }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: {{ .Values.image.repository }}/examples-bookinfo-productpage-v1:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

---
