apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: book-info-health-check
  namespace: {{ .Values.namespace }}
spec:
  default:
    checkIntervalSec: {{ .Values.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.healthCheck.unhealthyThreshold }}
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.healthCheck.port }}
        requestPath: {{ .Values.healthCheck.requestPath }}
  targetRef:
    group: ""
    kind: Service
    name: productpage
---

