{{- range list "details" "ratings" "reviews" "productpage" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-{{ . }}
  namespace: {{ $.Values.namespace }}
  labels:
    account: {{ . }}
{{- end }}

---
