name: Terraform GCP

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Destroy?'
        required: true
        default: false
        type: boolean  

env:
  TF_VERSION: 1.8.0

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
      pull-requests: write # Allows the workflow to comment on PRs

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GCP Auth
      uses: google-github-actions/auth@v3
      with:
        project_id: project-f53962c2-b852-4294-a0f
        service_account: github-actions-sa@project-f53962c2-b852-4294-a0f.iam.gserviceaccount.com
        workload_identity_provider: projects/776566261695/locations/global/workloadIdentityPools/github/providers/my-repo

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: terraform/network
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform/network
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy != true
      working-directory: terraform/network
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy != true
      working-directory: terraform/network
      run: terraform apply tfplan

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == true
      working-directory: terraform/network
      run: terraform destroy -auto-approve
