name: Terraform GCP

on:
  workflow_dispatch:

env:
  TF_VERSION: '1.8.0'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
      pull-requests: write # Allows the workflow to comment on PRs

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GCP Auth
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'project-f53962c2-b852-4294-a0f'
        workload_identity_provider: 'projects/776566261695/locations/global/workloadIdentityPools/github/providers/my-repo'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: terraform/network
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform/network
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform/network
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform/network
      run: terraform apply tfplan
